apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  labels:
    cleanup.kyverno.io/ttl: 24h
  name: policy-exc-req-f9447x1040n-0
spec:
  exceptions:
  - policyName: disallow-capabilities
    ruleNames:
    - adding-capabilities
    - autogen-adding-capabilities
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        names:
        - kindnet
        - kube-proxy
        namespaces:
        - kube-system
    - resources:
        kinds:
        - ReplicaSet
        names:
        - coredns-5d78c9869d
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Pod
        names:
        - coredns-5d78c9869d-47h9n
        - etcd-kind-control-plane
        - kindnet-kw9wr
        - kube-apiserver-kind-control-plane
        - coredns-5d78c9869d-h5bn4
        - kube-controller-manager-kind-control-plane
        - kube-scheduler-kind-control-plane
        - kube-proxy-655rk
        namespaces:
        - kube-system
    - resources:
        kinds:
        - Deployment
        names:
        - coredns
        namespaces:
        - kube-system
